import Link from "./HardLink"; import type { FAQ } from "../../data/site"; import type { Service } from "../../data/services"; import type { Location } from "../../data/locations"; import { site } from "../../data/site";
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((x,i)=><span key={x.label}>{i>0&&<b aria-hidden="true">/</b>}{x.href?<Link href={x.href}>{x.label}</Link>:x.label}</span>)}</nav>}
export function PageHero({eyebrow,title,lead}:{eyebrow:string;title:string;lead:string}){return <section className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{lead}</p><div className="hero-actions"><Link className="btn" href="/request-service" data-cta="page-hero-request">Request Service</Link><a className="inline-link" href={site.phoneHref} data-cta="page-hero-call">Call {site.phone} →</a></div></div><div className="page-hero-art" aria-hidden="true"><span>BR</span></div></section>}
export function SectionHead({eyebrow,title,lead}:{eyebrow?:string;title:string;lead?:string}){return <div className="section-head">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{lead&&<p>{lead}</p>}</div>}
export function ServiceGrid({items}:{items:Service[]}){return <div className="card-grid">{items.map((s,i)=><article className="service-card" key={s.slug}><span className="card-number">{String(i+1).padStart(2,"0")}</span><p className="kicker">{s.category}</p><h3>{s.name}</h3><p>{s.summary}</p><Link href={`/services/${s.slug}`}>Explore {s.name} <span aria-hidden="true">→</span></Link></article>)}</div>}
export function AreaServiceGrid({items,location}:{items:Service[];location:Location}){return <div className="area-service-grid">{items.map(s=><Link key={s.slug} href={`/service-areas/${location.slug}/${s.slug}`}><span>{s.category}</span><h3>{s.name} in {location.name}</h3><p>{s.summary}</p><b>View local service →</b></Link>)}</div>}
export function LocationGrid({items}:{items:Location[]}){return <div className="location-grid">{items.map(l=><Link className="location-card" href={`/service-areas/${l.slug}`} key={l.slug}><span>{l.state}</span><h3>{l.name}</h3><p>{l.region}</p><b aria-hidden="true">→</b></Link>)}</div>}
export function FAQList({items}:{items:FAQ[]}){return <div className="faq-list">{items.map((f,i)=><details key={f.question} open={i===0}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div>}
export function CTA({title="Ready to talk about your plumbing needs?",text="Tell us what is happening and where. We’ll follow up to confirm coverage and discuss the next step.",id="section-request"}:{title?:string;text?:string;id?:string}){return <section className="cta"><div><p className="eyebrow">Bear River Plumbing</p><h2>{title}</h2><p>{text}</p></div><div><Link className="btn btn-light" href="/request-service" data-cta={id}>Request Service</Link><a href={site.phoneHref} data-cta={`${id}-call`}>Call {site.phone}</a></div></section>}
const benefitIcons = {
  clock:<><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></>,
  message:<><path d="M4 5h16v11H9l-5 4V5Z"/><path d="m8 9 8 4M16 9l-8 4"/></>,
  dollar:<><circle cx="12" cy="12" r="8"/><path d="M14.5 8.5h-3a2 2 0 0 0 0 4h1a2 2 0 0 1 0 4h-3M12 6.5v2m0 8v2"/></>,
  clean:<><path d="M9 4h6l1 4 3 2v9H5v-9l3-2 1-4Z"/><path d="M9 13h6M8 16h8"/></>,
  calendar:<><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4m8-4v4M4 10h16m-9 4 1.5 1.5L16 12"/></>,
  shield:<><path d="M12 3 5 6v5c0 4.6 2.9 7.9 7 10 4.1-2.1 7-5.4 7-10V6l-7-3Z"/><path d="m9 12 2 2 4-4"/></>
};
const benefits=[["clock","Two-Hour Appointment Windows"],["message","No Sales Pitch"],["dollar","$0 Dispatch Fee"],["clean","Clean & Respectful Technicians"],["calendar","Same-Day Appointments"],["shield","Licensed & Insured"]] as const;
export function TrustBar(){return <section className="trust-bar" aria-label="Customer benefits">{benefits.map(([icon,label])=><div key={label}><svg viewBox="0 0 24 24" aria-hidden="true">{benefitIcons[icon]}</svg><strong>{label}</strong></div>)}</section>}
