import Link from "./HardLink"; import type { FAQ } from "../../data/site"; import type { Service } from "../../data/services"; import type { Location } from "../../data/locations"; import { site } from "../../data/site";
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((x,i)=><span key={x.label}>{i>0&&<b aria-hidden="true">/</b>}{x.href?<Link href={x.href}>{x.label}</Link>:x.label}</span>)}</nav>}
export function PageHero({eyebrow,title,lead}:{eyebrow:string;title:string;lead:string}){return <section className="page-hero"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="lead">{lead}</p><div className="hero-actions"><Link className="btn" href="/request-service" data-cta="page-hero-request">Request Service</Link><a className="inline-link" href={site.phoneHref} data-cta="page-hero-call">Call {site.phone} →</a></div></div><div className="page-hero-art" aria-hidden="true"><span>BR</span></div></section>}
export function SectionHead({eyebrow,title,lead}:{eyebrow?:string;title:string;lead?:string}){return <div className="section-head">{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h2>{title}</h2>{lead&&<p>{lead}</p>}</div>}
export function ServiceGrid({items}:{items:Service[]}){return <div className="card-grid">{items.map((s,i)=><article className="service-card" key={s.slug}><span className="card-number">{String(i+1).padStart(2,"0")}</span><p className="kicker">{s.category}</p><h3>{s.name}</h3><p>{s.summary}</p><Link href={`/services/${s.slug}`}>Explore {s.name} <span aria-hidden="true">→</span></Link></article>)}</div>}
export function AreaServiceGrid({items,location}:{items:Service[];location:Location}){return <div className="area-service-grid">{items.map(s=><Link key={s.slug} href={`/service-areas/${location.slug}/${s.slug}`}><span>{s.category}</span><h3>{s.name} in {location.name}</h3><p>{s.summary}</p><b>View local service →</b></Link>)}</div>}
export function LocationGrid({items}:{items:Location[]}){return <div className="location-grid">{items.map(l=><Link className="location-card" href={`/service-areas/${l.slug}`} key={l.slug}><span>{l.state}</span><h3>{l.name}</h3><p>{l.region}</p><b aria-hidden="true">→</b></Link>)}</div>}
export function FAQList({items}:{items:FAQ[]}){return <div className="faq-list">{items.map((f,i)=><details key={f.question} open={i===0}><summary>{f.question}<span aria-hidden="true">+</span></summary><p>{f.answer}</p></details>)}</div>}
export function CTA({title="Ready to talk about your plumbing needs?",text="Tell us what is happening and where. We’ll follow up to confirm coverage and discuss the next step.",id="section-request"}:{title?:string;text?:string;id?:string}){return <section className="cta"><div><p className="eyebrow">Bear River Plumbing</p><h2>{title}</h2><p>{text}</p></div><div><Link className="btn btn-light" href="/request-service" data-cta={id}>Request Service</Link><a href={site.phoneHref} data-cta={`${id}-call`}>Call {site.phone}</a></div></section>}
export function TrustBar(){return <section className="trust-bar"><div><strong>Family Owned</strong><span>Local roots and personal service</span></div><div><strong>Residential Plumbing</strong><span>Repairs, upgrades, and home systems</span></div><div><strong>New Construction</strong><span>Plumbing coordination for new homes</span></div><div><strong>Quality Workmanship</strong><span>Care for the work and the property</span></div></section>}
